version: "3"
services:
  nodejs_app:
    container_name: bbkal-node
    build:
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      mynetwork:
        ipv4_address: 172.9.0.4
  mysql:
    image: mysql:latest
    container_name: bbkal-db
    environment:
      MYSQL_ROOT_PASSWORD: calvin
      MYSQL_DATABASE: web
    ports:
      - "3306:3306"
    volumes:
      - bbkaldata:/var/lib/mysql
    networks:
      mynetwork:
        ipv4_address: 172.9.0.3
volumes:
  bbkaldata:
    external: true
networks:
  mynetwork:
    name: mynetwork
    driver: bridge
    ipam:
      config:
        - subnet: 172.9.0.0/16
